version: '3.8'

services:
  frontend:
    build:
      context: ./client/noiseremover 
      dockerfile: Dockerfile
    container_name: springboot-frontend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "127.0.0.1:8001:8000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
